version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/kinda
    command: sh -c "cd kinda-fr && yarn dev"
    ports:
      - "3000:3000"
